version: '3.5'

services:
  nginx:
    image: nginx:1.19-alpine
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
    ports:
      - 80:80
  pgsql:
    image: postgres:13.2-alpine
    restart: unless-stopped
    environment:
      POSTGRES_PASSWORD: dog321
    container_name: db_pgsql
    volumes:
     - ./database:/var/lib/postgresql/data
  redis:
    image: redis
    ports:
      - 6379:6379
    volumes:
     - ./cache:/data
  frontend:
    image: exfront
    ports:
      - 5000:5000
  backend:
    image: exback
    ports:
      - 8080:8080
    environment:
      - REQUEST_ORIGIN=http://localhost
      - REDIS_HOST=redis
      - POSTGRES_HOST=pgsql
      - POSTGRES_PASSWORD=dog321
