version: '3.5'

services:
  frontend:
    build: ./material-applications/example-frontend
    image: exfront
    ports:
      - 5000:5000
  backend:
    build: ./material-applications/example-backend
    image: exback
    ports:
      - 8080:8080
