version: "3"
services:
  tinyurl:
    image: charlesfu4/tinyurl 
    ports:
      - 4000:3001
    container_name: tinyurl 
  watchtower:
    image: containrrr/watchtower
    environment:
      - WATCHTOWER_POLL_INTERVAL=60 # Poll every 60 seconds
      - WATCHTOWER_MONITOR_ONLY=true
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    container_name: watchtower